[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
multistake = "2mgSDKAjDo8fQN6oms6YzczHhyeYEJunTzxjQgegYADf"

[programs.devnet]
multistake = "2mgSDKAjDo8fQN6oms6YzczHhyeYEJunTzxjQgegYADf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[provider.devnet]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"

